"use client";

import { useActionState, useState } from "react";
import type { Pendencia, Prioridade } from "@/lib/pendencias";
import { criarPendencia, reabrirPendencia, type PendenciaState } from "./actions";

const input = "mt-1.5 w-full rounded-xl border border-[#172033]/15 bg-white px-3.5 py-2.5 text-sm outline-none focus:border-[#6366F1] focus:ring-2 focus:ring-[#6366F1]/25";
function Reabrir({ projetoId, tarefa }: { projetoId: string; tarefa: Pendencia }) { const [estado, action, pendente] = useActionState<PendenciaState, FormData>(reabrirPendencia.bind(null, projetoId, tarefa.id), {}); return <form action={action}>{estado.erro && <p role="alert" className="mb-2 text-sm text-red-600">{estado.erro}</p>}<button type="submit" disabled={pendente} className="text-sm font-semibold text-[#6366F1] disabled:opacity-60">{pendente ? "Reabrindo..." : "Reabrir pendência"}</button></form>; }

export default function PendenciasProjeto({ projetoId, integrantes, pendencias }: { projetoId: string; integrantes: { id: string; nome: string | null }[]; pendencias: Pendencia[] }) {
  const [estado, action, pendente] = useActionState<PendenciaState, FormData>(criarPendencia.bind(null, projetoId), {});
  const [prioridadeSelecionada, setPrioridade] = useState<Prioridade>("media");
  const abertas = pendencias.filter((item) => item.status === "pendente"); const concluidas = pendencias.filter((item) => item.status !== "pendente");
  return <section className="mt-8 max-w-4xl rounded-xl border border-[#172033]/10 bg-white p-4 shadow-sm sm:rounded-2xl sm:p-6"><h2 className="text-xl font-bold">Pendências</h2><p className="mt-2 text-sm text-[#172033]/60">Registre os próximos passos da orientação para este projeto.</p>
    <form action={action} aria-busy={pendente} className="mt-5 border-b border-[#172033]/10 pb-6"><fieldset disabled={pendente} className="space-y-4"><legend className="text-sm font-semibold">Nova pendência</legend><div><label htmlFor="descricao" className="block text-sm font-medium">Descrição</label><textarea id="descricao" name="descricao" required maxLength={5000} rows={3} className={input} /></div><div className="grid gap-4 sm:grid-cols-2"><div><label htmlFor="prioridade" className="block text-sm font-medium">Prioridade</label><select id="prioridade" name="prioridade" value={prioridadeSelecionada} onChange={(event) => setPrioridade(event.target.value as Prioridade)} className={input}><option value="baixa">Baixa</option><option value="media">Média</option><option value="alta">Alta</option></select></div><div><label htmlFor="prazo" className="block text-sm font-medium">Prazo <span className="text-[#172033]/50">(opcional)</span></label><input id="prazo" name="prazo" type="date" className={input} /></div></div><div><label htmlFor="responsavel_id" className="block text-sm font-medium">Responsável</label><select id="responsavel_id" name="responsavel_id" defaultValue="" className={input}><option value="">Projeto / grupo</option>{integrantes.map((item) => <option key={item.id} value={item.id}>{item.nome || "Aluno sem nome"}</option>)}</select></div></fieldset>{estado.erro && <p role="alert" className="mt-4 text-sm text-red-600">{estado.erro}</p>}{estado.sucesso && <p role="status" className="mt-4 text-sm text-[#15803D]">{estado.sucesso}</p>}<button type="submit" disabled={pendente} className="mt-5 rounded-xl bg-[#6366F1] px-5 py-2.5 text-sm font-semibold text-white hover:bg-[#4F52D9] disabled:opacity-60">{pendente ? "Criando..." : "Criar pendência"}</button></form>
    <div className="mt-6"><h3 className="font-semibold">Em aberto</h3>{abertas.length ? <ul className="mt-3 space-y-3">{abertas.map((item) => <li key={item.id} className="rounded-xl border border-[#172033]/10 p-4"><div className="flex flex-wrap justify-between gap-2"><span className="font-medium">{item.descricao}</span><span className="text-xs font-semibold text-[#6366F1]">{item.prioridade}</span></div><p className="mt-2 text-sm text-[#172033]/60">Responsável: {item.responsavel || "Projeto / grupo"} · Prazo: {item.prazo || "Sem prazo"}</p></li>)}</ul> : <p className="mt-3 text-sm text-[#172033]/60">Nenhuma pendência em aberto.</p>}</div>
    <div className="mt-6"><h3 className="font-semibold">Concluídas</h3>{concluidas.length ? <ul className="mt-3 space-y-3">{concluidas.map((item) => <li key={item.id} className="rounded-xl border border-[#172033]/10 bg-[#F5F7FA] p-4"><p className="font-medium">{item.descricao}</p><p className="mt-2 text-sm text-[#172033]/60">Responsável: {item.responsavel || "Projeto / grupo"} · Concluída em: {item.resolvida_em || "Data não informada"}</p><div className="mt-3"><Reabrir projetoId={projetoId} tarefa={item} /></div></li>)}</ul> : <p className="mt-3 text-sm text-[#172033]/60">Nenhuma pendência concluída.</p>}</div>
  </section>;
}