"use client";

import { useActionState, useEffect } from "react";
import { analisarVersaoComTess, type TessVersaoState } from "./tess-actions";

export default function TessVersionActions({ versaoId, onDraft }: { versaoId: string; onDraft: (texto: string) => void }) {
  const [estado, action, processando] = useActionState<TessVersaoState, FormData>(analisarVersaoComTess.bind(null, versaoId), {});
  useEffect(() => { if (estado.modo === "rascunho" && estado.resposta) onDraft(estado.resposta); }, [estado.modo, estado.resposta, onDraft]);
  return <section className="mt-5 border-t border-[#172033]/10 pt-5"><h2 className="text-lg font-bold">✨ Apoio da Tess</h2><p className="mt-1 text-sm text-[#172033]/60">As ações geram sugestões para revisão do professor. Nada é publicado automaticamente.</p><div className="mt-4 flex flex-wrap gap-3"><form action={action}><input type="hidden" name="modo" value="resumo" /><button type="submit" disabled={processando} className="rounded-xl border border-[#6366F1]/30 px-4 py-2.5 text-sm font-semibold text-[#6366F1] disabled:opacity-60">Resumir com Tess</button></form><form action={action}><input type="hidden" name="modo" value="comparacao" /><button type="submit" disabled={processando} className="rounded-xl border border-[#6366F1]/30 px-4 py-2.5 text-sm font-semibold text-[#6366F1] disabled:opacity-60">Comparar com anterior</button></form><form action={action}><input type="hidden" name="modo" value="rascunho" /><button type="submit" disabled={processando} className="rounded-xl bg-[#6366F1] px-4 py-2.5 text-sm font-semibold text-white disabled:opacity-60">Criar rascunho de devolutiva</button></form></div>{processando && <p className="mt-3 text-sm text-[#172033]/60">A Tess está analisando...</p>}{estado.erro && <p role="alert" className="mt-3 text-sm text-red-600">{estado.erro}</p>}{estado.resposta && <div className="mt-4 rounded-xl border border-[#6366F1]/20 bg-[#6366F1]/5 p-4"><p className="text-xs font-semibold uppercase tracking-wide text-[#6366F1]">{estado.modo === "rascunho" ? "Rascunho sugerido pela Tess" : "Sugestão da Tess"}</p><p className="mt-2 whitespace-pre-wrap text-sm leading-6">{estado.resposta}</p>{estado.modo === "rascunho" && <p className="mt-3 text-xs text-[#172033]/60">O texto foi colocado no formulário abaixo para sua revisão.</p>}</div>}</section>;
}