"use client";

import Link from "next/link";
import { useActionState } from "react";
import type { TessContext, TessConversation, TessMessage } from "@/lib/ai/tess/types";
import { novaConversaTess } from "./actions";
import TessComposer from "./TessComposer";
import TessContextBadge from "./TessContextBadge";
import TessMessageView from "./TessMessage";

export default function TessChat({ role, conversas, conversa, mensagens, contexto }: { role: "aluno" | "professor"; conversas: TessConversation[]; conversa: TessConversation | null; mensagens: TessMessage[]; contexto: TessContext }) {
  const [novaEstado, novaAction, criando] = useActionState(novaConversaTess.bind(null, contexto.contextType, contexto.contextId), {});
  return <main className="min-h-screen bg-[#F5F7FA] px-4 py-6 text-[#172033] sm:px-6 sm:py-8 lg:px-10"><header className="border-b border-[#172033]/10 pb-6"><p className="text-sm font-medium text-[#6366F1]">Assistente acadêmica</p><h1 className="mt-1 text-3xl font-bold">Tess Studio</h1><p className="mt-2 text-sm text-[#172033]/60">Converse com a Tess usando o contexto autorizado da sua orientação.</p></header><div className="mt-8 grid gap-5 lg:grid-cols-[240px_minmax(0,1fr)_260px]"><aside className="rounded-2xl border border-[#172033]/10 bg-white p-4 shadow-sm"><div className="flex items-center justify-between"><h2 className="font-semibold">Conversas</h2><form action={novaAction}><button type="submit" disabled={criando} className="text-sm font-semibold text-[#6366F1] disabled:opacity-60">{criando ? "..." : "Nova"}</button></form></div>{novaEstado.erro && <p role="alert" className="mt-3 text-sm text-red-600">{novaEstado.erro}</p>}{!conversas.length ? <p className="mt-4 text-sm text-[#172033]/60">Nenhuma conversa ainda.</p> : <ul className="mt-4 space-y-2">{conversas.map((item) => <li key={item.id}><Link href={`/${role}/tess?conversa=${encodeURIComponent(item.id)}`} className={`block rounded-lg px-3 py-2 text-sm ${item.id === conversa?.id ? "bg-[#6366F1]/10 font-semibold text-[#6366F1]" : "hover:bg-[#F5F7FA]"}`}>{item.titulo}</Link></li>)}</ul>}</aside><section className="flex min-h-[560px] flex-col overflow-hidden rounded-2xl border border-[#172033]/10 bg-[#F5F7FA] shadow-sm">{conversa ? <><div className="border-b border-[#172033]/10 bg-white px-5 py-4"><h2 className="font-semibold">{conversa.titulo}</h2><p className="mt-1 text-xs text-[#172033]/60">As respostas são sugestões e não substituem a decisão acadêmica.</p></div><div className="flex-1 space-y-4 overflow-y-auto p-5">{mensagens.length ? mensagens.map((item, index) => <TessMessageView key={item.id ?? `${item.role}-${index}`} mensagem={item} />) : <p className="rounded-xl border border-dashed border-[#172033]/20 bg-white p-5 text-sm text-[#172033]/60">Comece perguntando o que precisa de atenção no seu TCC.</p>}</div><TessComposer conversaId={conversa.id} /></> : <div className="flex flex-1 flex-col items-center justify-center p-8 text-center"><p className="text-4xl">✨</p><h2 className="mt-3 text-xl font-bold">Comece uma conversa com a Tess</h2><p className="mt-2 max-w-md text-sm text-[#172033]/60">Use o botão Nova para criar uma conversa com o contexto acadêmico atual.</p><form action={novaAction}><button type="submit" disabled={criando} className="mt-5 rounded-xl bg-[#6366F1] px-5 py-2.5 text-sm font-semibold text-white disabled:opacity-60">{criando ? "Criando..." : "Nova conversa"}</button></form></div>}</section><aside><TessContextBadge contexto={contexto} /></aside></div></main>;
}